#!/usr/bin/env bash
#Bash script that loops from 1 to 10 and:
# .displays bad luck for the 4th loop iteration
# .displays good luck for the 8th loop iteration
# .displays Best School for the other iterations

counter=0

while [ $counter -le 9 ]
do
	if [ $counter = 3 ]
	then
		echo "bad luck"
	elif [ $counter = 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	counter=$((counter + 1))
done
